name: CI

on:
  pull_request:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libusb-1.0-0-dev cppcheck
      - name: Build
        run: make
      - name: Static analysis
        run: cppcheck --enable=warning,style *.c
